# Accounting Journal System Configuration
# PDF Processing and OCR Settings

# PDF Processing
pdf:
  # Right column zoom for credit side recognition improvement
  right_col_zoom: true
  # DPI settings for image conversion
  dpi: 180
  # Pages per split for processing
  pages_per_split: 5

# LLM Provider Settings
llm:
  provider: gemini            # "anthropic" | "gemini" | "openai"
  model: gemini-2.5-flash     # Latest Gemini 2.5 Flash (fastest, most cost-effective)
  temperature: 0.0
  right_col_zoom: false       # Right column zoom flag (moved from pdf section)

# Pricing table (USD per token, editable)
pricing:
  anthropic:
    claude-3-5-sonnet-20240620: {in: 0.000003, out: 0.000015}  # Legacy
    claude-3-5-haiku-20240307:  {in: 0.000001, out: 0.000005}  # Legacy
    claude-sonnet-4-20250514:   {in: 0.000003, out: 0.000015}  # Latest Claude Sonnet 4
  gemini:
    gemini-1.5-pro:   {in: 0.0000015, out: 0.000005}  # Legacy
    gemini-1.5-flash: {in: 0.0000003, out: 0.0000006}  # Legacy
    gemini-2.5-flash: {in: 0.0000003, out: 0.0000006}  # Latest Gemini 2.5 Flash
    gemini-2.5-pro:   {in: 0.0000015, out: 0.000005}   # Latest Gemini 2.5 Pro
  openai:
    gpt-5:      {in: 0.000005, out: 0.000015}  # Latest GPT-5
    gpt-5-mini: {in: 0.000001, out: 0.000003}  # Latest GPT-5 Mini

# Legacy Claude API Settings (for backward compatibility)
claude:
  # Model configuration
  model: "claude-sonnet-4-20250514"
  max_tokens: 4096
  temperature: 0
  # Enhanced prompt for right column recognition
  enhanced_prompts: true

# Processing Settings
processing:
  # Two-stage processing order
  front_stage_reconcile: true
  back_stage_finalize_only: true
  # Zero count exception handling
  zero_count_exception: true
  # Diagnostic snapshots
  diag_snapshots: true

# Logging
logging:
  # Force INFO level logs
  level: "INFO"
  # Singleton initialization
  singleton: true
  # Stage-based diagnostic logging
  stage_logging: true

# UI Settings
ui:
  # Show processing metrics
  show_metrics: true
  # Metrics to display
  metrics:
    - empty_codes_excluded
    - duplicates_excluded
    - one_vs_many_splits
    - left_right_swaps
    - unassigned_codes
    - sum_rows_dropped